import fs from 'node:fs/promises'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { fileURLToPath } from 'node:url'

const execFileAsync = promisify(execFile)

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const repoRoot = path.resolve(__dirname, '..')

const generatedRelativePath = 'src/data/eventPressureNotes.generated.json'
const candidatesRelativePath = 'src/data/eventPressureCandidates.generated.json'
const generatedPath = path.join(repoRoot, generatedRelativePath)
const candidatesPath = path.join(repoRoot, candidatesRelativePath)
const markdownPath = path.join(repoRoot, 'event-pressure-promotion-report.md')

const shouldWriteMarkdown = process.argv.includes('--markdown')

async function readJson(filePath, fallback) {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8'))
  } catch (error) {
    if (error.code === 'ENOENT') return fallback
    throw error
  }
}

async function readHeadJson(relativePath, fallback) {
  try {
    const { stdout } = await execFileAsync('git', ['show', `HEAD:${relativePath}`], {
      cwd: repoRoot,
      maxBuffer: 1024 * 1024 * 10,
    })
    return JSON.parse(stdout)
  } catch {
    return fallback
  }
}

function byId(items) {
  return new Map(items.map((item) => [item.id, item]))
}

function isDifferent(a, b) {
  return JSON.stringify(a) !== JSON.stringify(b)
}

function formatList(values) {
  if (!Array.isArray(values) || values.length === 0) return '-'
  return values.join(', ')
}

function formatLinks(note) {
  const links = note.verifyLinks || []
  if (links.length === 0) return '-'

  return links.map((link) => `${link.label || 'Source'} · ${link.url}`).join('\n')
}

function noteBlock(note, index, label = 'Added note') {
  return [
    `### ${index + 1}. ${label}: ${note.city} · ${note.title}`,
    '',
    `- id: \`${note.id}\``,
    `- dates: ${note.startDate} to ${note.endDate}`,
    `- category: ${note.category}`,
    `- pressure: ${note.pressureLevel}`,
    `- confidence: ${note.confidence}`,
    `- source checked at: ${note.sourceCheckedAt}`,
    `- state: ${note.state || '-'}`,
    `- venue: ${note.venue || '-'}`,
    `- affected areas: ${formatList(note.affectedAreas)}`,
    '',
    'Source:',
    '',
    formatLinks(note),
    '',
    'Traveler impact:',
    '',
    `> ${note.travelerImpact || '-'}`,
    '',
    'Recommended action:',
    '',
    `> ${note.recommendedAction || '-'}`,
    '',
  ].join('\n')
}

function candidateBlock(candidate, index) {
  return [
    `### ${index + 1}. Removed candidate: ${candidate.city} · ${candidate.title}`,
    '',
    `- id: \`${candidate.id}\``,
    `- detected from: ${candidate.detectedFrom || '-'}`,
    `- dates: ${candidate.startDate || '-'} to ${candidate.endDate || '-'}`,
    `- source: ${candidate.sourceLabel || '-'} · ${candidate.sourceUrl || '-'}`,
    '',
  ].join('\n')
}

function buildMarkdown({ addedNotes, updatedNotes, removedCandidates, remainingCandidates }) {
  const lines = [
    '# Event pressure promotion review',
    '',
    'This PR was generated by the event pressure candidate promotion workflow.',
    '',
    'Please review source links, dates, wording and confidence before merging.',
    '',
    '## Summary',
    '',
    `- Added generated notes: ${addedNotes.length}`,
    `- Updated generated notes: ${updatedNotes.length}`,
    `- Removed promoted candidates: ${removedCandidates.length}`,
    `- Remaining candidates: ${remainingCandidates.length}`,
    '',
  ]

  if (addedNotes.length === 0 && updatedNotes.length === 0 && removedCandidates.length === 0) {
    lines.push('No promotion changes detected.', '')
    return lines.join('\n')
  }

  if (addedNotes.length > 0) {
    lines.push('## Added generated notes', '')
    addedNotes.forEach((note, index) => lines.push(noteBlock(note, index, 'Added note')))
  }

  if (updatedNotes.length > 0) {
    lines.push('## Updated generated notes', '')
    updatedNotes.forEach((note, index) => lines.push(noteBlock(note, index, 'Updated note')))
  }

  if (removedCandidates.length > 0) {
    lines.push('## Removed promoted candidates', '')
    removedCandidates.forEach((candidate, index) => lines.push(candidateBlock(candidate, index)))
  }

  lines.push(
    '## Review checklist',
    '',
    '- [ ] Dates match the official source.',
    '- [ ] Source link is official and reachable.',
    '- [ ] Wording does not imply live crowd, live train or live shop status.',
    '- [ ] Impact and action are useful for English-speaking Germany travelers.',
    '- [ ] Generated note is future/current, not expired.',
    '',
  )

  return lines.join('\n')
}

async function main() {
  const [baseNotes, currentNotes, baseCandidates, currentCandidates] = await Promise.all([
    readHeadJson(generatedRelativePath, []),
    readJson(generatedPath, []),
    readHeadJson(candidatesRelativePath, []),
    readJson(candidatesPath, []),
  ])

  for (const [name, value] of [
    ['base notes', baseNotes],
    ['current notes', currentNotes],
    ['base candidates', baseCandidates],
    ['current candidates', currentCandidates],
  ]) {
    if (!Array.isArray(value)) {
      throw new Error(`${name} must be an array.`)
    }
  }

  const baseNoteMap = byId(baseNotes)
  const currentNoteMap = byId(currentNotes)
  const baseCandidateMap = byId(baseCandidates)
  const currentCandidateMap = byId(currentCandidates)

  const addedNotes = currentNotes.filter((note) => !baseNoteMap.has(note.id))
  const updatedNotes = currentNotes.filter((note) => {
    const baseNote = baseNoteMap.get(note.id)
    return baseNote && isDifferent(baseNote, note)
  })
  const removedCandidates = baseCandidates.filter((candidate) => !currentCandidateMap.has(candidate.id))
  const remainingCandidates = currentCandidates

  const markdown = buildMarkdown({
    addedNotes,
    updatedNotes,
    removedCandidates,
    remainingCandidates,
  })

  console.log(markdown)

  if (shouldWriteMarkdown) {
    await fs.writeFile(markdownPath, markdown)
    console.log(`Wrote ${path.relative(repoRoot, markdownPath)}`)
  }

  if (currentNoteMap.size < baseNoteMap.size) {
    throw new Error('Generated note count decreased. Promotion workflow should not remove generated notes.')
  }

  if (removedCandidates.some((candidate) => currentCandidateMap.has(candidate.id))) {
    throw new Error('Removed candidate comparison failed.')
  }
}

main().catch((error) => {
  console.error(error.message || error)
  process.exit(1)
})
